name: Default
kind: pipeline
type: docker

trigger:
  branch:
    - master

steps:
  - name: Node.js CI
    image: node:18
    commands:
      - npm ci
      - npm run build --if-present
      - npm run lint
